spring:
  profiles:
    active: dev

---
server:
  port: 8001
spring:
  application:
    name: USER-SERVICE
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 8002
spring:
  application:
    name: USER-SERVICE
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/